name: R Image Creator
author: Roche/Genentech - Insights Engineering
description: Create R images on demand, given a base R image, a set of system dependencies, and an renv lock file.

inputs:
  image-name:
    description: name of the image that will be stored into ghcr
    required: false
    default: "rocker/rstudio:4.3.0"
  repository-owner:
    description: Repository owner (image will be pushed on ghcr/repository-owner)
    required: true
  repo-user:
    description: User access project container registry. Github variable `github.actor` can be used.
    required: true
  repo-token:
    description: Token to access project container registry. Github variable `GITHUB_TOKEN` can be used.
    required: true
  tag:
    description: |
      Custom Image Tag/Version. Defaults to current date in the `YYYY.MM.DD` format if unspecified.
    required: false
    default: ""
  tag-latest:
    description: Tag image as `latest`
    default: false
    required: false
    type: boolean
  base-image:
    description: 'Base image'
    required: false
    default: 'rocker/rstudio:4.3.0'
  sysdeps:
    description: |
      A list of system dependencies to install on the image.
      This should be a comma-separated list of sysdeps.
      Eg: 'libxml2,adoptopenjdk-8,tcltk'
      Note that the sysdeps name should be OS-specific.
      Right now, only Debian OSes (installable via apt) are supported.
    required: false
    default: ''
  renv-lock-file:
    description: |
      A location of an renv.lock file that should be restored on the image.
      This can also be a remote location (i.e. a GitHub raw URL etc).
    required: false
    default: ''
  packages:
    description: |
      A comma-separated list of R packages that should be installed on the image. Dependencies will be fetched from the 'repos' option specified below.
      Eg: 'pharmaverse/admiral,pharmaverse/admiralonco,dplyr'
    required: false
    default: ''
  repos:
    description: |
      A comma-separated set of R package repository URLs that can be used for getting dependencies for the 'packages' installed.
      Eg: 'https://cloud.r-project.org,https://cran.r-project.org'
    required: false
    default: 'https://cloud.r-project.org'
  platforms:
    description: |
      A comma-separated list of platforms e.g. `linux/amd64,linux/arm64` that should be supported in Build job.'
    required: false
    default: 'linux/amd64'
  renv-version:
    description: |
      A renv version used to restore an environment.'
    required: false
    default: '1.0.3'

branding:
  icon: 'image'
  color: 'red'

runs:
  using: "composite"
  steps:
    - name: Define tag
      id: tag
      run: |
        tag="${{ inputs.tag }}"
        if [ -z "${tag}" ]
        then
          tag=$(date +%Y.%m.%d)
        fi
        echo "tag=${tag}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      id: buildx
      with:
        install: true

    - name: Cache Docker layers ♻️
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.image-name }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.image-name }}

    - name: Log in to the Container registry 🗝
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.repo-user }} # ${{ github.actor }}
        password: ${{ inputs.repo-token }} # ${{ secrets.GITHUB_TOKEN }}

    - name: Set build variables 📐
      id: build_vars
      run: |
        # Set Image name
        image_name="${{ inputs.image-name }}"
        tag="${{ steps.tag.outputs.tag }}"
        tag_latest="${{ inputs.tag-latest }}"

        # Set full image name
        full_names="ghcr.io/${{ inputs.repository-owner }}/${image_name}:${tag}"
        if [ "${tag_latest}" == "true" ]
        then
          full_names="$full_names,ghcr.io/${{ inputs.repository-owner }}/${image_name}:latest"
        fi
        echo "FULL_NAMES=${full_names}" >> $GITHUB_OUTPUT

        # get current action dockerfile path
        echo "${{ github.action_path }}"
        ls -al "${{ github.action_path }}"
        echo "DOCKERFILE_PATH=${{ github.action_path }}/Dockerfile" >> $GITHUB_OUTPUT

        # copy scripts directory on top
        cp -r "${{ github.action_path }}/scripts" ./

        # if input renv-lock-file specified, check if renv.lock file exists locally - else try to download it
        if [ ! -z "${{ inputs.renv-lock-file }}" ]
        then
          script_path="${{ github.action_path }}/scripts/get_renv_file.sh"
          cp $script_path ./
          chmod +x ./get_renv_file.sh
          ./get_renv_file.sh "${{ inputs.renv-lock-file }}"
        fi
        echo "debug trace: /scripts/install_all.sh ${{ inputs.sysdeps }} ${{ inputs.renv-lock-file }} ${{ inputs.packages }} ${{ inputs.repos }} ${{ inputs.renv-version}}"

      shell: bash

    - name: Build and push image 🏗
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ${{ steps.build_vars.outputs.DOCKERFILE_PATH }}
        push: true
        tags: ${{ steps.build_vars.outputs.FULL_NAMES }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        build-args: |
          BASE_IMAGE=${{ inputs.base-image }}
          SYSDEPS=${{ inputs.sysdeps }}
          RENV_LOCK=${{ inputs.renv-lock-file }}
          OTHER_PKG=${{ inputs.packages }}
          REPOS=${{ inputs.repos }}
        platforms: ${{ inputs.platforms }} 

    - name: Move cache ♻️
      run: |
        rm -rf /tmp/.buildx-cache
        if [ -f /tmp/.buildx-cache-new ]
        then {
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        }
        fi
      shell: bash
